### ISSUE TITLE
How to set default options per instance?

### ISSUE THREAD

**Issue by Synchro** [smokills/laravel-http-client-default-options#3]
In Guzzle I can do this:

```php
        $this->client = new Client(
            [
                'base_uri' => 'https://www.example.com',
                'headers' => [
                    'some' => 'header',
                ],
            ]
        );
```

I do that in a base class common to several different subclasses that call APIs relative to this common base URL.

I'm looking at switching to the built-in Http Laravel class, and found your package while looking for how to do this. From your docs I can only see that you allow setting these options globally, across all instances of the Http client, which I don't want to do as I have other scripts that don't need those defaults, or per-request, which is messy. So I'm looking to create an instance on which I can set default properties.

I've tried using:

```php
        $this->client = (new Http())->withOptions(
            [
                'base_uri' => 'https://www.example.com',
                'headers' => [
                    'some' => 'header',
                ],
            ]
        );
```
but that doesn't seem to work as it expects a request rather than a client instance. Is this possible? Is there another way? Or should I stick with native Guzzle?

**Comment by smokills** [comment]
Hi. First of all I wanna thank you for getting interest in my package, and sorry for the (very) late answer.

The aim of this package is not what you are searching for. This package only alloy you to share common option among the same instance.

If you need this kind of specific behaviour, you'll need to wrap each client in a separate class or a container instance.
